# Generated by Django 5.1.6 on 2025-10-15 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50, verbose_name='شهر های قابل ارسال')),
                ('state', models.CharField(max_length=50, verbose_name='استان')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='وضعیت فعال/غیر فعال')),
            ],
            options={
                'verbose_name': 'شهرو استان ',
                'verbose_name_plural': 'شهر ها و استانها ',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='order_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_city', to='orders.city', verbose_name='شهر محل ارسال سفارش'),
        ),
    ]
