# Generated by Django 5.1.6 on 2025-10-16 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_city_order_order_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='state',
        ),
    ]
