# Generated by Django 5.1.6 on 2025-10-16 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_city_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=30, verbose_name='استان')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='وضعیت فعال/غیر فعال')),
            ],
            options={
                'verbose_name': 'استان ',
                'verbose_name_plural': 'استان ها',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_city', to='orders.state', verbose_name='استان شهر'),
        ),
    ]
