# Generated by Django 5.1.6 on 2025-10-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_state_city_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'شهرو استان ', 'verbose_name_plural': 'شهر ها '},
        ),
        migrations.AddField(
            model_name='order',
            name='codeposti',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='کدپستی'),
        ),
    ]
