# Generated by Django 5.1.6 on 2025-10-16 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_city_options_order_codeposti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_city',
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_state', to='orders.state', verbose_name='استان'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
