# Generated by Django 5.1.6 on 2025-10-18 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_brand_image_name_alter_product_image_name_and_more'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouses',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wearehouse_products', to='products.product', verbose_name='کالا'),
        ),
    ]
