# Generated by Django 5.1.6 on 2025-10-19 19:27

import django.db.models.deletion
import utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0016_alter_brand_image_name_alter_product_image_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(max_length=100, verbose_name='نام مقاله')),
                ('image_name', models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='تصویر مقاله')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت فعال/غیرفعال')),
                ('blog_text', models.TextField(verbose_name='متن مقاله')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان درج')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ انتشار')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_blog', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده مقاله')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_product', to='products.product')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
    ]
