# Generated by Django 5.1.6 on 2025-10-19 20:38

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_slug_alter_blog_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image_name',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='تصویر مقاله'),
        ),
    ]
