# Generated by Django 5.1.6 on 2025-10-19 20:52

import django.db.models.deletion
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_blog_title_alter_blog_image_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100, verbose_name='نام گروه')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت فعال/غیرفعال')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان درج')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='اسلاگ گروه ')),
            ],
            options={
                'verbose_name': 'گروه مقاله',
                'verbose_name_plural': 'گروهای مقالات',
            },
        ),
        migrations.AlterField(
            model_name='blog',
            name='image_name',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='تصویر مقاله'),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_group', to='blog.bloggroup', verbose_name='والد مقاله'),
        ),
    ]
