# Generated by Django 5.1.6 on 2025-10-19 21:09

import django.db.models.deletion
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_bloggroup_alter_blog_image_name_blog_blog_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_group1', to='blog.bloggroup', verbose_name='والد مقاله'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image_name',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='تصویر مقاله'),
        ),
    ]
