# Generated by Django 5.1.6 on 2025-10-19 21:12

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_blog_group_alter_blog_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blog_group',
        ),
        migrations.AlterField(
            model_name='blog',
            name='image_name',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='تصویر مقاله'),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_group',
            field=models.ManyToManyField(blank=True, null=True, related_name='blog_group1', to='blog.bloggroup', verbose_name='والد مقاله'),
        ),
    ]
