# Generated by Django 5.1.6 on 2025-10-18 20:27

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0002_alter_slider_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='image_name',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='تصویراسلاید'),
        ),
        migrations.DeleteModel(
            name='Scoring',
        ),
    ]
